use_frameworks!

platform :ios, '9.0'

target 'ModuloDetalhes_Example' do
  pod 'ModuloDetalhes', :path => '../'

  target 'ModuloDetalhes_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
